server:
  port: 8201

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.158.91:3306/shequ-acl?characterEncoding=utf-8&useSSL=false
    username: root
    password: root3306
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8